### ISSUE TITLE
The Swipeable View goes off the edge of its parent view when swiped back into position.

### ISSUE THREAD

**Issue by tomriddle25** [VictorAlbertos/SwipeCoordinator#2]
The swipeable view goes off the edge of the parent view when swiped back into position.
Steps to produce -
1) start swiping the view,
2) stop and go back in the direction of its initial position.
3) when you try to put it in its initial position the view goes off the edge and gets cut.
![whatsapp image 2018-03-07 at 2 19 31 pm](https://user-images.githubusercontent.com/17904436/37082915-d7072578-2213-11e8-8a1e-350125ece98e.jpeg)
![whatsapp image 2018-03-07 at 2 19 30 pm](https://user-images.githubusercontent.com/17904436/37082919-d9abcef0-2213-11e8-8210-5111e57beb53.jpeg)

**Comment by VictorAlbertos** [comment]
I'm not able to replicate it, please if you are still interested in this issue create a minimal project where this can be replicated. Thanks.
